name: cronjob

on: workflow_dispatch 

jobs:
  build:
    name: Cloud Run Deployment
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@master

      - name: Setup GCP Service Account
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: 'latest'
          service_account_email: ${{ secrets.GCP_SA_EMAIL }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Configure Docker
        run: |
          gcloud auth configure-docker
      - name: Build
        run: |
          docker build -t asia.gcr.io/${{ secrets.GCP_PROJECT_ID }}/dailybrieftw:latest .
      - name: Push
        run: |
          docker push asia.gcr.io/${{ secrets.GCP_PROJECT_ID }}/dailybrieftw:latest
      - name: Deploy
        run: |
          gcloud run deploy dailybrieftw \
          --region asia-east1 \
          --memory 3G \
          --image asia.gcr.io/${{ secrets.GCP_PROJECT_ID }}/dailybrieftw \
          --add-cloudsql-instances ${{ secrets.INSTANCE_CONNECTION_NAME }} \
          --update-env-vars INSTANCE_CONNECTION_NAME="${{ secrets.INSTANCE_CONNECTION_NAME }}",CLOUD_SQL_CONNECTION_NAME="${{ secrets.INSTANCE_CONNECTION_NAME }}",DB_USER="${{ secrets.DB_USER }}",DB_PWD="${{ secrets.DB_PWD }}",DB_NAME="${{ secrets.DB_NAME }}",TTS_MODEL_DIR="${{ secrets.TTS_MODEL_DIR }}" \
          --platform managed \
          --allow-unauthenticated \
          --project ${{ secrets.GCP_PROJECT_ID }}
  
